<?xml version="1.0"?>

<!DOCTYPE cyclos-changelog [
    <!-- Root element -->
    <!ELEMENT cyclos-changelog (version+)>

    <!-- Version descriptor -->
    <!ELEMENT version (
        description?,
        enhancements?,
        bug-fixes?,
        new-libraries?,
        removed-libraries?,
        new-helps?,
        removed-helps?,
        new-static-files?,
        removed-static-files?,
        new-translation-keys?,
        removed-translation-keys?,
        new-setup-keys?,
        removed-setup-keys?,
        new-css-classes?,
        removed-css-classes?,
        statements*,
        migration*
    )>
    <!ATTLIST version label CDATA #REQUIRED>

    <!-- Optional version description -->
    <!ELEMENT description (#PCDATA)>

    <!--
        Database statements to be applied if autoSchemaUpgrade is enabled.
        The required database attribute indicates the database name (same as the returned
        by java.sql.DatabaseMetaData.getDatabaseProductName(), but case insensitive)
        that the statements apply.
    -->
    <!ELEMENT statements (item*)>
    <!ATTLIST statements database CDATA #REQUIRED>

    <!--
        A migration class to be executed
    -->
    <!ELEMENT migration EMPTY>
    <!ATTLIST migration database CDATA #REQUIRED>
    <!ATTLIST migration class CDATA #REQUIRED>

    <!-- Contains a list of new / modified features -->
    <!ELEMENT enhancements (item*)>

    <!-- Contains a list of bug fixes -->
    <!ELEMENT bug-fixes (item*)>

    <!-- Contains a list of new help files -->
    <!ELEMENT new-helps (item*)>

    <!-- Contains a list of removed help files -->
    <!ELEMENT removed-helps (item*)>

    <!-- Contains a list of new static files -->
    <!ELEMENT new-static-files (item*)>

    <!-- Contains a list of removed static files -->
    <!ELEMENT removed-static-files (item*)>

    <!-- Contains a list of new translation keys -->
    <!ELEMENT new-translation-keys (item*)>

    <!-- Contains a list of removed translation keys -->
    <!ELEMENT removed-translation-keys (item*)>

    <!-- Contains a list of new translation keys on the setup package -->
    <!ELEMENT new-setup-keys (item*)>

    <!-- Contains a list of removed translation keys on the setup package -->
    <!ELEMENT removed-setup-keys (item*)>

    <!-- Contains a list of new CSS classes -->
    <!ELEMENT new-css-classes (item*)>

    <!-- Contains a list of removed CSS classes -->
    <!ELEMENT removed-css-classes (item*)>

    <!-- A list item -->
    <!ELEMENT item (#PCDATA)>
]>

<cyclos-changelog>

	<version label="3.7.3">
		<enhancements>
			<item>Changed the hibernate.default_batch_fetch_size to 1 by default (previously, was 20). Now, Cyclos takes up much less memory, at minimum cost of performance.</item>
			<item></item>
		</enhancements>

		<bug-fixes>
			<item>An unexpected exception could cause the Lucene indexing thread to be interrupted, resulting in no more indexes being updated</item>
			<item>There was a possible error while indexing members</item>
			<item>There could be errors when exporting data (member, member records, ads) with custom fields of type member autocomplete</item>
			<item>On PosWeb receive payment, when selecting the empty option for payment type, an error was being displayed</item>
			<item>A bug introduced in 3.7.2 prevented members from editing their own profile if there were custom fields marked as unique</item>
			<item>Custom fields with mask and flagged as unique were not correctly checked for uniqueness, making the validation always pass</item>
			<item>Payment custom fields which are marked as unique Ignore unique validation on payment custom field when transaction was cancelled or denied</item>
			<item>Custom fields of type URL were not being correctly validated</item>
			<item>Caches were not being correctly invalidated when deactivating an advertisement category, leading to inactive categories being shown on the advertisement search</item>
		</bug-fixes>

		<statements database="mysql">
			<item></item>
        </statements>
	</version>


	<version label="3.7.2">
		<enhancements>
			<item>New custom field type: member</item>
			<item>Added a new option in member custom field on both Member search and Advertisements search: web services. So, the field can be used on web services searches without showing up on the application.</item>
			<item>Improved some database connection pool configurations in cyclos.properties</item>
			<item>Now the application root url (used on generated links) is no longer configured on the cyclos.properties file, but on the application itself (in local settings), and can be customized by group or group filter</item>
			<item>Added a broker filter for administrators searching member records</item>
		</enhancements>

		<bug-fixes>
			<item>It was not possible to repay a loan from another account using the same currency as the loan destination account</item>
			<item>Transfer types with permission are not returned when trying to perform a payment as user without permission to view system accounts</item>
			<item>Rest webservice payment with percentage fees shows wrong amount at payment confirmation</item>
			<item>Application error on member payment at amount validation when no payment type is provided</item>
			<item>Possible application error on mobile login</item>
			<item>Searching via web services using enumerated custom fields with multiple values was broken</item>
			<item>The search indexes for member records could have stale data when updating the owner member (be aware that it takes a few seconds to update the indexes)</item>
			<item>Transfer types on group permissions are not correct when changing visible accounts / groups and there are TTs marked as priority</item>
			<item>If a member registration take a long time to be completed another new member could be registered with the same values avoiding the uniqueness restriction of some values (username, email, custom field marked as unique)</item>
			<item>When removing an account from a group, if a member had it's limit for that account changed, the task which would deactivate the accounts failed</item>
		</bug-fixes>

		<statements database="mysql">
			<item>alter table custom_field_values add column member_value_id integer</item>
			<item>alter table custom_field_values add index FK8AE18A15B1DE9525 (member_value_id), add constraint FK8AE18A15B1DE9525 foreign key (member_value_id) references members (id);</item>
			<item>alter table groups add column root_url varchar(100)</item>
			<item>alter table group_filters add column root_url varchar(100)</item>
        </statements>

        <migration database="mysql" class="nl.strohalm.cyclos.setup.migrations.version3_7.RootUrlMigration" />
	</version>

	<version label="3.7.1">
		<enhancements>
			<item>New url: [root]/do/redirect?name=loginPageName&amp;path=redirectPath which will set the login page cookie for customizations and then redirect to the given path</item>
			<item>Added min amount limit to transfer type</item>
			<item>When confirming a payment, if there are fees which deduct from total amount, a total amount field is now displayed</item>
			<item>On the make payment page, now the payment type name is always shown, even if there is only a single possible option</item>
			<item>On the make payment page, the possible currencies (when multiple) are only shown after selecting the destination member, to avoid showing currencies there would be no possible payment types</item>
			<item>Added an option on the payment type to control to which kind of users parent / child transactions will be visible</item>
			<item>Increased the maximum length of both payment type and transaction fees to 100 characters</item>
			<item>Added a group setting to not show the currency on payments, but all payment types directly</item>
			<item>The result list on external account history was changed to be more like the regular account history, including adding a member column</item>
			<item>The 'pending' status filter on external account history has been split in pending and complete and incomplete</item>
			<item>When importing external payments, the line number is retained, and no longer will appear file import errors, but the transactions will be imported anyway, and import comments will be generated for each error</item>
			<item>Added support for the first authorization level of system to member payments to be authorized by the receiver</item>
			<item>For loans with interests, it is no longer possible to pay intermediate amounts, as fees were never calculated over partial amounts</item>
		</enhancements>

		<bug-fixes>
		    <item>The chargeback permissions were not being correctly controlled by the receiving account</item>
			<item>Error when searching for advertisements in web services using member custom fields as filters</item>
			<item>When accessing the login page as guest while using url parameter for group-customized layout, there could happen errors on the log</item>
			<item>Deadlock when using HazelcastLockHandler when performing an scheduled payment with the first expiration date for today</item>
			<item>After importing an external payment with an empty payment type, if there was a single possible payment type, it was not possible to save the record</item>
			<item>The login page fields were too large</item>
			<item>When the current e-mail was empty and e-mail change validation was being used, there was an error while trying to set an e-mail for a member</item>
			<item>Member custom fields with update / visibility access to 'Members not at registration' which were marked as required always led public registrations to fail validation</item>
			<item>Under high concurrency, even when account locking was enabled, it was possible to exceed the maximum amount per day (set on the payment type)</item>
			<item>Removed members were being returned on the autocomplete fields if admins could manage such groups</item>
			<item>When the payment type has a maximum amount per day, a scheduled payment total amount was being checked at the current date, not each installment on the respective due date</item>
			<item>When advertisement description contents had HTML comments, a broken layout could be produced on the advertisement list, if the text truncation would en in the middle of the comments</item>
			<item>For new databases, the rest (mobile phone application) channel was not set as default to members</item>
		</bug-fixes>

		<statements database="mysql">
        	<item>alter table transfer_types add column min_amount decimal(15,6)</item>
        	<item>alter table transfer_types add column tx_hierarchy_visibility varchar(1)</item>
        	<item>update transfer_types set tx_hierarchy_visibility='M' where tx_hierarchy_visibility is null</item>
        	<item>alter table groups add column hide_currency_on_pmt bit default false not null</item>
        	<item>alter table external_transfers add column line_number integer, add column comments longtext</item>
        </statements>
	</version>

	<version label="3.7">
		<enhancements>
			<item>The default theme has more space between elements, and the default thumbnail dimension is now 100x100 for new databases</item>
			<item>Now, when moving a member from group if he has scheduled payments we don't throw an exception, instead, we cancel all payments and notify the related members</item>
			<item>New quick access icon: search members</item>
			<item>Added the option to search advertisements using web services using group filters</item>
			<item>Now when the url parameter for a group filter is used, the public registration will only list possible groups within that group filter</item>
		</enhancements>

		<bug-fixes>
			<item>On flat member records results with rich text custom fields, only for the first result the value was displayed</item>
			<item>Was not possible to change a member from group if there were pending system/member scheduled payments even if the new group has the same accounts</item>
			<item>When registering a new member in public registration, customized files for the chosen group will be used</item>
			<item>If a member had a disabled account from a previous group, then that same account type is added to his current group, he might get duplicated accounts</item>
			<item>It was not possible to remove a group without users if it previously had an user</item>
			<item>Members in different groups which could see each other were getting permission denied errors when attempting to send an invoice from the profile</item>
			<item>On the admin home page, the number of connected users included users not visible by the admin</item>
			<item>When a broker or administrator registered a member with e-mail validation enabled, and there was no permission to view pending members, a permission denied was immediately displayed after the registration</item>
			<item>On some messages from broker to registered members, on the messages list / details the destination was not being correctly displayed</item>
			<item>There was too much margin besides images in edit profile / ad pages</item>
			<item>If the system clock is set to a past date, the account balances are no longer wrong because of daily calculated balances</item>
   			<item>Some notifications generated from scheduled payments (processed, canceled, etc) were not sent</item>
			<item>Some pages displayed a link to a user profile even if the logged user didn't have permission to access that profile</item>
			<item>Newly created databases didn't take into account the default log path (in cyclos.properties) for web services or rest log files</item>
			<item>Change pin menu appearing for member with access to no channels using pin and without permission to modify the channel access</item>
			<item>Admins with permission to view a specific member record type was getting permission denied if the view member record types</item>
			<item>When using an url parameter for group / group filter customizations, some pages displayed to the guest were still not using the expected customizations</item>
		</bug-fixes>

		<new-translation-keys>
			<item>createMember.created.pending</item>
			<item>customField.ad.visibility.WEB_SERVICE</item>
			<item>customImage.system.quickAccess_searchMembers</item>
			<item>quickAccess.searchMembers</item>
			<item>settings.message.scheduledPaymentsCancelled</item>
			<item>settings.message.scheduledPaymentsCancelledToOther</item>
		</new-translation-keys>

		<removed-translation-keys>
			<item>alert.system.NULL_RATE</item>
			<item>changeGroup.error.move.hasPendingScheduledPayments</item>
			<item>changeGroup.error.remove.hasPendingScheduledPayments</item>
		</removed-translation-keys>

		<new-setup-keys>
			<item>settings.message.scheduled-payments-cancelled-to-other.body</item>
			<item>settings.message.scheduled-payments-cancelled-to-other.sms</item>
			<item>settings.message.scheduled-payments-cancelled-to-other.subject</item>
			<item>settings.message.scheduled-payments-cancelled.body</item>
			<item>settings.message.scheduled-payments-cancelled.sms</item>
			<item>settings.message.scheduled-payments-cancelled.subject</item>
		</new-setup-keys>

        <statements database="mysql">
        	<item>delete from images where subclass='sys' and name='dropdown.gif'</item>
        	<item>update messages set type='a2g' where direction='O' and type='brk' and from_member_id is not null</item>
        	<item>insert into settings (type, name, value) values ('local', 'maxThumbnailHeight', '80')</item>
        	<item>insert into settings (type, name, value) values ('local', 'maxThumbnailWidth', '80')</item>
        	<item>update scheduled_payments set show_to_receiver=true where show_to_receiver=false and id in (select i.scheduled_payment_id from invoices as i where i.scheduled_payment_id is not null)</item>
        </statements>
	</version>

	<version label="3.7_RC1">
		<enhancements>
			<item>Now e-mail validation can be configured in a more fine-grained way under member groups</item>
			<item>Now e-mail validation is used not only to register new members, but also when changing the e-mail</item>
			<item>Now, in case of locking errors on commit, the transaction is retried. This makes using Galera MySQL cluster more reliable.</item>
			<item>Via local settings, the member search result list can now be sorted chronological (on creation date) or alphabetical</item>
			<item>Brokers can now export their member list to CSV</item>
			<item>Added support for REST services, adding a new built-in channel for that</item>
			<item>Added group filter to the statistics pages</item>
			<item>Improvements and fixes in Hazelcast usage, providing better cluster support</item>
			<item>Now we use a thread pool to execute code in a new transaction (instead of create a new thread each time)</item>
			<item>Better memory management, releasing some acquired resources on shutdown, which helps preventing memory leaks</item>
			<item>Removed the optimize indexes functionality, as it is no longer recommended by Lucene, the full-text engine used by Cyclos</item>
			<item>Member custom fields where not being returned when loading an advertisement by id in web services</item>
			<item>Improved internals of how messages are sent to groups</item>
			<item>System images are no longer limited to the maximum image dimensions (in local settings)</item>
			<item>New member permission to change external access</item>
			<item>Added support (cyclos properties parameter) to create sms data when populate the db from scratch</item>
			<item>New bulk action to enable/disable access channels</item>
			<item>The box shadows on the default theme were too dark in chrome and IE. Please, re-apply the theme in order to get this update.</item>
		</enhancements>

		<bug-fixes>
		 	<item>Having disabled scheduling tasks a NullPointerException was being thrown when trying to save the local settings with a different scheduling task time</item>
		 	<item>Deadlock when making payments with lock in all (from and to) accounts</item>
		 	<item>There was an error when attempting to accept an invoice with multiple possible payment types</item>
		 	<item>There was an error if the cyclos.lockHandler.timeoutSeconds property had an space right after the number</item>
		 	<item>The local receipt printing was incorrectly escaping characters, leading to wrong print data</item>
		 	<item>Create new ad / edit ad shows category fields in wrong order</item>
		 	<item>Error when confirming an e-mail address (by clicking the link in the e-mail) after registration</item>
		 	<item>View Profile page may render distorted in case of hidden or empty fields.</item>
		 	<item>External transfers with no member resulted in NullPointerException</item>
		 	<item>Sometimes an error occurred when validating a member registration via e-mail</item>
		 	<item>Change member channels form gave admins/brokers with no persmission the impression that they had permission to change channels</item>
		 	<item>Changing a custom member field control to RTF didn't stop it from being hideable. Now making it to an RTF stops it from being hideable.</item>
		 	<item>When making a custom member field unhideable, existing instances of the field still remained hidden.</item>
		 	<item>If stylesheets couldn't be located, the application startup failed on a NullPointerException. With the fix it just starts, though images will not be loadable.</item>
		 	<item>State reports on a time in history showed data for which there is no history record available.</item>
		 	<item>State reports on a time in history now shows the date of the results.</item>
		 	<item>The height of options in a multi drop down was not correct</item>
			<item>The configuration (show in result/search) for linked payment custom fields was not take into account</item>
		 	<item>In a cluster, modifying translation keys don't immediately propagate changes to other nodes</item>
		 	<item>Values for custom fields no longer related to a member group were still being returned on advertisement searches</item>
		 	<item>Rich text custom fields with fixed width elements could break the view profile page if the contents were too large</item>
		 	<item>Removed members should never be returned on bulk actions</item>
		 	<item>In standalone with HSQLDB database, it was not possible to access the account history</item>
		</bug-fixes>

		<new-libraries>
			<item>cxf-2.6.1.jar</item>
			<item>ehcache-core-2.6.0.jar</item>
			<item>hazelcast-2.2.jar</item>
			<item>hibernate-3.6.10.jar</item>
			<item>jackson-all-1.9.6.jar</item>
			<item>javassist-3.12.0.GA.jar</item>
			<item>lucene-analyzers-3.6.1.jar</item>
			<item>lucene-core-3.6.1.jar</item>
			<item>lucene-misc-3.6.1.jar</item>
			<item>lucene-queries-3.6.1.jar</item>
			<item>neethi-3.0.2.jar</item>
			<item>org.springframework.aop-3.1.2.RELEASE.jar</item>
			<item>org.springframework.asm-3.1.2.RELEASE.jar</item>
			<item>org.springframework.beans-3.1.2.RELEASE.jar</item>
			<item>org.springframework.context-3.1.2.RELEASE.jar</item>
			<item>org.springframework.context.support-3.1.2.RELEASE.jar</item>
			<item>org.springframework.core-3.1.2.RELEASE.jar</item>
			<item>org.springframework.expression-3.1.2.RELEASE.jar</item>
			<item>org.springframework.jdbc-3.1.2.RELEASE.jar</item>
			<item>org.springframework.orm-3.1.2.RELEASE.jar</item>
			<item>org.springframework.transaction-3.1.2.RELEASE.jar</item>
			<item>org.springframework.web-3.1.2.RELEASE.jar</item>
			<item>org.springframework.web.servlet-3.1.2.RELEASE.jar</item>
			<item>spring-security-config-3.1.0.RELEASE.jar</item>
			<item>spring-security-core-3.1.0.RELEASE.jar</item>
			<item>spring-security-web-3.1.0.RELEASE.jar</item>
			<item>xmlschema-core-2.0.2.jar</item>
		</new-libraries>

		<removed-libraries>
			<item>cxf-2.4.4.jar</item>
			<item>ehcache-core-2.4.6.jar</item>
			<item>hazelcast-1.9.4.8.jar</item>
			<item>hibernate-3.6.8.jar</item>
			<item>javassist-3.9.0.jar</item>
			<item>lucene-analyzers-3.4.0.jar</item>
			<item>lucene-core-3.4.0.jar</item>
			<item>lucene-misc-3.4.0.jar</item>
			<item>lucene-queries-3.4.0.jar</item>
			<item>neethi-3.0.0.jar</item>
			<item>neethi-3.0.1.jar</item>
			<item>org.springframework.aop-3.0.6.RELEASE.jar</item>
			<item>org.springframework.asm-3.0.6.RELEASE.jar</item>
			<item>org.springframework.beans-3.0.6.RELEASE.jar</item>
			<item>org.springframework.context-3.0.6.RELEASE.jar</item>
			<item>org.springframework.context.support-3.0.6.RELEASE.jar</item>
			<item>org.springframework.core-3.0.6.RELEASE.jar</item>
			<item>org.springframework.expression-3.0.6.RELEASE.jar</item>
			<item>org.springframework.jdbc-3.0.6.RELEASE.jar</item>
			<item>org.springframework.orm-3.0.6.RELEASE.jar</item>
			<item>org.springframework.transaction-3.0.6.RELEASE.jar</item>
			<item>org.springframework.web-3.0.6.RELEASE.jar</item>
			<item>xmlschema-core-2.0.1.jar</item>
		</removed-libraries>

		<new-translation-keys>
			<item>accountHistory.creditsDebitsBalance.amount</item>
			<item>adminTasks.indexes.status.ACTIVE</item>
			<item>alert.member.NEGATIVE_VIRTUAL_RATED_BALANCE</item>
			<item>alert.member.negativeVirtualRatedBalance</item>
			<item>alert.system.ACCOUNT_FEE_CANCELLED</item>
			<item>alert.system.ACCOUNT_FEE_FAILED</item>
			<item>alert.system.ACCOUNT_FEE_RECOVERED</item>
			<item>alert.system.NEGATIVE_VIRTUAL_RATED_BALANCE</item>
			<item>alert.system.NULL_RATE</item>
			<item>alert.system.RATE_INITIALIZATION_FAILED</item>
			<item>alert.system.negativeVirtualRatedBalance</item>
			<item>alert.system.rateInitializationFailed</item>
			<item>changeChannels.disableChannels</item>
			<item>changeChannels.enableChannels</item>
			<item>changeChannels.invalidChannelsSelection</item>
			<item>customField.confirmUnhide</item>
			<item>customField.type.DECIMAL</item>
			<item>customImage.system.mobileSplash_large</item>
			<item>customImage.system.mobileSplash_medium</item>
			<item>customImage.system.mobileSplash_small</item>
			<item>global.nothingSelected</item>
			<item>group.settings.emailValidation.ADMIN</item>
			<item>group.settings.emailValidation.BROKER</item>
			<item>group.settings.emailValidation.USER</item>
			<item>group.settings.emailValidation.WEB_SERVICE</item>
			<item>member.bulkActions.changeChannels</item>
			<item>member.bulkActions.changeChannels.confirmation</item>
			<item>member.bulkActions.channelsChanged</item>
			<item>member.bulkActions.channelsChangedForAll</item>
			<item>member.bulkActions.channelsNotChanged</item>
			<item>menu.member.personal.changePin</item>
			<item>mobile.welcomeMessage</item>
			<item>permission.adminMemberBulkActions.changeChannels</item>
			<item>permission.memberAccess.changeChannelsAccess</item>
			<item>profile.error.changeEmailValidationFailed</item>
			<item>profile.modified.emailPending</item>
			<item>profile.pendingEmail</item>
			<item>profile.pendingEmail.confirmed</item>
			<item>profile.pendingEmail.link</item>
			<item>profile.pendingEmail.resent</item>
			<item>profile.pendingEmailLastSent</item>
			<item>reports.current.presentation.result.at</item>
			<item>reports.stats.groupOfGroups</item>
			<item>settings.local.language.CZECH</item>
			<item>settings.local.memberSortOrder</item>
			<item>settings.local.memberSortOrder.ALPHABETICAL</item>
			<item>settings.local.memberSortOrder.CHRONOLOGICAL</item>
			<item>settings.log.restFile</item>
			<item>settings.log.restLevel</item>
			<item>settings.mail.smtpPassword</item>
			<item>settings.mail.smtpPort</item>
			<item>settings.mail.smtpServer</item>
			<item>settings.mail.smtpUseTLS</item>
			<item>settings.mail.smtpUsername</item>
			<item>smsMailing.error.variableNotFound</item>
			<item>smsMailing.systemName</item>
			<item>smsMailing.variables</item>
			<item>viewChannels.title.of</item>
		</new-translation-keys>

		<removed-translation-keys>
			<item>adminTasks.indexOptimizeEnqueued</item>
			<item>adminTasks.indexes.optimize</item>
			<item>adminTasks.indexes.optimizeAll</item>
			<item>adminTasks.indexes.status.NOT_OPTIMIZED</item>
			<item>adminTasks.indexes.status.OPTIMIZED</item>
			<item>alert.system.INDEX_OPTIMIZED</item>
			<item>alert.system.indexOptimized</item>
			<item>customField.type.BIG_DECIMAL</item>
			<item>group.settings.emailValidation.ALL</item>
			<item>group.settings.emailValidation.EXTERNAL</item>
			<item>group.settings.emailValidation.NEVER</item>
			<item>group.settings.emailValidation.PUBLIC</item>
			<item>group.settings.emailValidation.PUBLIC_BROKER</item>
			<item>message.emailsSent</item>
			<item>message.error.pendingMessagesToBeSent</item>
			<item>message.messagesSent</item>
			<item>message.stillSending</item>
			<item>settings.mail.smtp.password</item>
			<item>settings.mail.smtp.port</item>
			<item>settings.mail.smtp.server</item>
			<item>settings.mail.smtp.useTLS</item>
			<item>settings.mail.smtp.username</item>
		</removed-translation-keys>

		<new-setup-keys>
			<item>action.create-sms-data</item>
			<item>arg.create-sms-data</item>
			<item>channel.rest</item>
			<item>info-text.sample.body</item>
			<item>info-text.sample.subject</item>
			<item>service-client.controller.name</item>
			<item>sms-data.end</item>
			<item>sms-data.start</item>
			<item>transfer-type.sms-charge.description</item>
			<item>transfer-type.sms-charge.name</item>
			<item>transfer-type.sms-trade.description</item>
			<item>transfer-type.sms-trade.name</item>
		</new-setup-keys>

        <statements database="mysql">
        	<item>update custom_fields set type='decimal' where type='bigDecimal'</item>
        	<item>create table member_groups_email_validation (group_id integer not null, type char(1) not null, primary key (group_id, type)) ENGINE=InnoDB</item>
        	<item>alter table member_groups_email_validation add index FK9FC60562B45926EE (group_id), add constraint FK9FC60562B45926EE foreign key (group_id) references groups (id)</item>
        	<item>insert into member_groups_email_validation (group_id, type) select id, 'U' from groups where member_mail_validation in ('A', 'B', 'P', 'E')</item>
        	<item>insert into member_groups_email_validation (group_id, type) select id, 'B' from groups where member_mail_validation in ('A', 'B')</item>
        	<item>insert into member_groups_email_validation (group_id, type) select id, 'A' from groups where member_mail_validation in ('A')</item>
        	<item>insert into member_groups_email_validation (group_id, type) select id, 'W' from groups where member_mail_validation in ('A', 'E')</item>
        	<item>alter table groups drop column member_mail_validation</item>
        	<item>create table pending_email_changes (id integer not null auto_increment, creation_date datetime not null, member_id integer not null, by_id integer, new_email varchar(100) not null, validation_key varchar(64) not null, last_email_date datetime, remote_address varchar(100), primary key (id)) ENGINE=InnoDB</item>
        	<item>alter table pending_email_changes add index FK4B7C40782B1214C2 (by_id), add constraint FK4B7C40782B1214C2 foreign key (by_id) references members (id)</item>
        	<item>alter table pending_email_changes add index FK4B7C4078EAE0AB57 (member_id), add constraint FK4B7C4078EAE0AB57 foreign key (member_id) references members (id)</item>
        	<item>delete from index_operations where operation_type = 'OPT'</item>
        	<item>delete from alerts where msg_key = 'alert.system.indexOptimized'</item>
        	<item>alter table messages drop column messages_sent</item>
        	<item>alter table messages drop column emails_sent</item>
        	<item>alter table messages drop column finished</item>
        	<item>alter table messages add column email_sent bit not null</item>
        	<item>update messages set email_sent=true</item>
        	<item>drop table messages_pending_to_send</item>